### ISSUE TITLE
Feature: User can Learn about Crypto Currencies through a Video 

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/Crypto-Tracker#1]
## 📐 Functionality

> The user can view an introductory video to cryptocurrency when they open the app for the first time. 

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/70422100/121248041-cb182800-c857-11eb-8961-b2fb9c53d3d7.png)
![image](https://user-images.githubusercontent.com/70422100/121248095-dd926180-c857-11eb-8f34-7ae809e60b26.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create Index Html File
- [x] link the layout CSS file and the styles CSS  file to the HTML file
- [x] link the main.js file to the HTML file.
- [x] create a div with  container class
- [x] create a div with the class of row
- [x] Use a header to hold the Crypto logo
- [x] Add a search bar by having a text input and search button
- [x] create a new div with the class of row.
- [x] create the green alert 
- [x] place the chosen embedded Youtube Video 
- [x] create a button with the text close and the class of 'data-yt-off'
- [x] create a new div with the class of row
- [x] place an h3 with the text news.
- [x] apply the color for both the header and the alert div. 
- [x] apply the rest of the needed styles.
- [x] resize the Youtube video to an appropriate size.
- [x] In the main.js query the elements for the alert, youtube video and the 'close' button
- [x] in the main.js create a function that will hide the youtube video, alert box, and close button
- [x] check to see if everything is working as it should be.
