### ISSUE TITLE
User can look up different Crypto Currencies in a search bar

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/Crypto-Tracker#2]
## 📐 Functionality

> User will be able to look up a crypto coin.

## 🖼️ Wireframes
mobile
![image](https://user-images.githubusercontent.com/70422100/121409897-d67e5880-c916-11eb-9bd6-d1cc28a67329.png)
Desktop
![image](https://user-images.githubusercontent.com/70422100/121410413-691ef780-c917-11eb-8518-dce49de429ce.png)

## ✅ Task List
> ##### Commit checklist for tasks needed to complete the feature.
**HTML**
- [x] In the HTML create the DomTree that will be the outline for the live search feature (Desktop) and give the ul an id of #search-results
- [x] Create a search module that will show once the search button is clicked on mobile.
- [x] Give the search an id of #search
**CSS**
- [x] Give the styling needed to the Dom tree outline for both desktop and mobile.
**JS**
- [x] In the main.js use getElementById to target #search
- [x] Query the DOM for the #search-results
- [x] Create a function called ‘renderList’ that matches the dom tree you created earlier.
- [x] Create a new XHMLHttpRequest()
- [x] open() the xhr object to send a 'GET' request to the api url
- [x] Set the responseType to ‘JSON’
- [x] Log the status and response.
- [x] Create a new variable to contain the response.
- [x] Log the new variable to ensure that it contains the data needed.
- [x] Add an event listener of keyup to the #search
- [x] Log the event.target.value to make sure it matches the key pressed.
- [x] Loop through the variable containing the xhr.response
- [x] If the key entered matches a key value within the name property, then execute renderlist with the key value that it matches.  
- [x] Test to see if it is working correctly.
