### ISSUE TITLE
Feature: User can connect to cryptocurrency social media

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/Crypto-Tracker#22]
## ⚙️ Feature

User can connect to cryptocurrency social media

## ✅ Task List

- [ ] Create a new branch name "crypto-socials"
- [ ] find a twitter icon from iconify
- [ ] import the icon in the dom creation function
- [ ] wrap the icon in a <a> tag
- [ ] match the URL that will be tied to the coin based on the coin id. 
- [ ] test to see if the link works
- [ ] have it so it will open in a new web page
