### ISSUE TITLE
Feature: User can see data on the currency they selected

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/Crypto-Tracker#3]
## 📐 Functionality
User can see data on the currency they selected 

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/70422100/121600628-98a63080-c9f9-11eb-8a81-5ac5215f099f.png)
![image](https://user-images.githubusercontent.com/70422100/121600656-a22f9880-c9f9-11eb-9fe5-9f92be9bc954.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
HTML
- [x] Give the li of the search results a data-id of the coin id
- [x] Create the dom tree outline for the display of the coin data page
- [x] on each of the elements give a class of the data that is needed based on the xhr.response
CSS
- [x] apply the styling needed for both desktop and mobile
JS
- [x] console log the event target of the search drop down to ensure the data-id appears with the correct coin name
- [x] create the DOM tree with create element to make the outline you made with the correct classes.
- [x] pass in a coin to make sure that it is working correctly
- [x] create a function where the coins array will be looped to match the data-id
- [x] have it to that the coin data passes though to the function that will create the elements on the coin data page
- [x] test with different coins to enusre its working correctly
- [ ] debug any styling or js
