### ISSUE TITLE
Feature: User can see there favorite Crypto Currencies on there homepage

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/Crypto-Tracker#5]
## 📐 Functionality
Feature: User can see there favorite Crypto Currencies on there homepage

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/70422100/121719046-a8745200-ca97-11eb-9e92-c401f078bc06.png)
![image](https://user-images.githubusercontent.com/70422100/121719343-b9bd5e80-ca97-11eb-961e-f3e1a2851e2d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

HTML/CSS
- [x] create the DOM tree outline on the homepage where the favorite coin block will appear
- [x] create a ul with the class of favorite-coins
- [x] create a li with class of col-half
- [x] create an img and h3 element
- [x] style the listing to match the design

JS
- [x] create a function that will build the favorite coin list
- [x] add an event listener to on the "add to favorite" button that will hide the coin datapage and show the homescreen with the favorite coin rendered onto it.
- [x] In the data.js cthe data model to store the favorite coins selected and the state of the application
