### ISSUE TITLE
Feature: User can click there favorites on there homepage

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/Crypto-Tracker#6]
## ⚙️ Feature

When a user clicks on a coin in there favorite list, the coin data page will pop up.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/70422100/122263100-e7851780-ce8a-11eb-9f1f-c51a5cf058c1.png)
![image](https://user-images.githubusercontent.com/70422100/122263146-f4097000-ce8a-11eb-84eb-65225f10f424.png)

## ✅ Task List

- [x] create a variable that will be used to list to the click event.
- [x] Listen for clicks on the parent element of the rendered favorite list. 
- [x] log the event.target to ensure the coin-id matches the coin listed. 
- [x] show the coin data page once if one of the listings was clicked.
- [x] Pre-populate the coins data page with the clicked entry's values from the object found in the data model.
- [x] replace the "add to favorites" button with a "remove from favorites button for the next feature. 
- [x] remove all CSS styling that had no effect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
