### ISSUE TITLE
Feature: User can remove from favorite list

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/Crypto-Tracker#7]
## ⚙️ Feature

User can remove selected cryptocurrencies from the favorite list. 

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/70422100/122300015-99383e80-ceb3-11eb-8e35-61d3f7e9c0aa.png)
![image](https://user-images.githubusercontent.com/70422100/122300036-a2c1a680-ceb3-11eb-8f5c-3c6965e877f2.png)

## ✅ Task List

- [x] Add a click target for deleting a favorite from the favorite list.
- [x] Show a confirmation modal when a user clicks the deleted click target
- [x] Hide the modal if the user clicks cancel
- [x] Remove the favorite from the data model and from the DOM tree from the page if the user clicks Delete.
- [x] Show the updated favorite list.
- [x] Remove unnecessary CSS styling that had no affect
- [x] Test the functionality of the feature in a private browser session. 
- [x] Fix all errors.
