### ISSUE TITLE
Feature: User can see Cryptocurrency related news on there homage

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/Crypto-Tracker#8]
## ⚙️ Feature

 User can see Cryptocurrency related news on there homepage

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/70422100/122484741-1b933200-cf8a-11eb-83b1-9154e6c94f29.png)
![image](https://user-images.githubusercontent.com/70422100/122484787-382f6a00-cf8a-11eb-921c-74edccd62dba.png)

## ✅ Task List

- [x] In the HTML create the DomTree that will be the outline for the news section.
- [x] Give the styling needed to the Dom tree outline for both desktop and mobile.
- [x] In the main.js use getElementById to target #news-reel
- [x] Query the DOM for the #news-reel
- [x] Create a function called ‘renderNews’ that matches the dom tree you created earlier.
- [x]  Create a new XHMLHttpRequest()
- [x]  open() the xhr object to send a 'GET' request to the api url
- [x]  Set the responseType to ‘JSON’
- [x]  Log the status and response.
- [x] Create a DOM tree in JS to match tht html news section
- [x] match the new xhr response to the news tiles.
- [x] make sure the actually news link has a attirbute of `target="_blank"`
- [x] test to see if clicking the news link will open the article in a new tab
- [x] clean up the  css styling
- [x] fix any bugs
